# Generated by Django 2.1.1 on 2020-04-09 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_hooks', '0002_swappable_hook_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Hook',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hooks', to=settings.AUTH_USER_MODEL),
        ),
    ]
